# Generated by Django 6.0 on 2025-12-31 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(blank=True, max_length=100, null=True)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('units_consumed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, default=120.0, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='client.client')),
            ],
        ),
    ]
