# Generated by Django 6.0 on 2025-12-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='rate_per_unit',
            field=models.DecimalField(decimal_places=2, default=160.0, max_digits=10),
        ),
    ]
